### ISSUE TITLE
尋找是否有既有的測資

### ISSUE THREAD

**Issue by wush978** [wush978/recurrentR#2]
- 可公開的資料為佳
- 放入`data`資料夾

**Comment by ccwang002** [comment]
目前參考 Survival Analysis: A Self-Learning Text, 3rd by David G. Kleinbaum 一書的介紹，一般 recurrent survival data 會以 [Counting Process (CP) format](http://stat.ethz.ch/education/semesters/ss2011/seminar/contents/presentation_10.pdf) 呈現，資料表也可以直接用書上的。

**Comment by wush978** [comment]
我們也可以自己generate資料來測。

其實如果是要測試正確性的話，這應該是最正確的方式。

**Comment by wush978** [comment]
學姊有給一筆dataset

不過需要做格式的轉換

(需要認養)

沒人認養的話，寫完Huang 2004我會轉頭過來做

**Comment by ccwang002** [comment]
ok 我來認養！
