### ISSUE TITLE
Poisson Process Generator

### ISSUE THREAD

**Issue by wush978** [wush978/recurrentR#4]
用來產生測資，以及驗證用

**Comment by ccwang002** [comment]
現在 Poisson Process Generator 的實作放在 `inhomo_poisson` branch 中。

**Comment by ccwang002** [comment]
我把我對 WQC 2000 這篇 paper 對 `F(t)` estimator 的理解寫在這個文件中，放在 [RPubs](http://rpubs.com/ccwang002/7296) 上，並且自己用了一個簡單的 input data 來表達我對它的理解。

我現在最大的問題應該是不知道我這樣有沒有理解錯誤，我想我會同時開始 code 的實作，也許直接驗証之後就會知道正確與否。

EDIT: republish RPubs failed, upload to new url
EDIT: 增加可讀性

**Comment by wush978** [comment]
https://github.com/wush978/recurrentR/commit/79306c1871d806eaf96741e25d397c5d4922452d
