### ISSUE TITLE
Generator according to Hazard Function 

### ISSUE THREAD

**Issue by wush978** [wush978/recurrentR#5]

**Comment by ccwang002** [comment]
相關記錄放在 [Rpubs](http://rpubs.com/ccwang002/7394)

目前打算以這篇開始 http://epub.ub.uni-muenchen.de/1716/1/paper_338.pdf

**Comment by wush978** [comment]
http://www.demogr.mpg.de/papers/technicalreports/tr-2010-003.pdf

**Comment by ccwang002** [comment]
b4515e9 實作 [tr-2010-003](reference 其一) 的 generator

不過這個 generator 是針對 survival 設計，所以對一個 patient 只會有 one event time or censored 兩個情況。

會再把理論的部份補在 `doc/gen_hazard.test.Rmd`，確定後就會放入 `R/generator.R`

**Comment by wush978** [comment]
這部份要先移至RPPGen
